1. Write a program to reverse a string.

In [ ]:
def reverse_string(s):
    return s[::-1]

string = "Hello, World!"
reversed_string = reverse_string(string)
print(reversed_string)

2. Check if a string is a palindrome.

In [ ]:
def is_palindrome(s):
    s = s.lower().replace(" ", "")
    return s == s[::-1]

string = "A man a plan a canal Panama"
print(is_palindrome(string))

3. Convert a string to uppercase.

In [ ]:
def to_uppercase(s):
    return s.upper()

string = "hello, world!"
print(to_uppercase(string))

4. Convert a string to lowercase.

In [ ]:
def to_lowercase(s):
    return s.lower()

string = "HELLO, WORLD!"
print(to_lowercase(string))

5. Count the number of vowels in a string.

In [ ]:
def count_vowels(s):
    vowels = "aeiouAEIOU"
    return sum(1 for char in s if char in vowels)

string = "Hello, World!"
print(count_vowels(string))

6. Count the number of consonants in a string.

In [ ]:
def count_consonants(s):
    consonants = "bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ"
    return sum(1 for char in s if char in consonants)

string = "Hello, World!"
print(count_consonants(string))

7. Remove all whitespaces from a string.

In [ ]:
def remove_whitespaces(s):
    return s.replace(" ", "")

string = "Hello, World!"
print(remove_whitespaces(string))

In [ ]:
8. Find the length of a string without using the `len()` function.

In [ ]:
def string_length(s):
    count = 0
    for _ in s:
        count += 1
    return count

string = "Hello, World!"
print(string_length(string))

9. Check if a string contains a specific word.

In [ ]:
def contains_word(s, word):
    return word in s

string = "Hello, World!"
word = "World"
print(contains_word(string, word))

10. Replace a word in a string with another word.

In [ ]:
def replace_word(s, old_word, new_word):
    return s.replace(old_word, new_word)

string = "Hello, World!"
old_word = "World"
new_word = "Universe"
print(replace_word(string, old_word, new_word))

11. Count the occurrences of a word in a string.

In [ ]:
def count_word_occurrences(s, word):
    return s.split().count(word)

string = "hello world hello"
word = "hello"
print(count_word_occurrences(string, word))

12. Find the first occurrence of a word in a string.

In [ ]:
def first_occurrence(s, word):
    return s.find(word)

string = "Hello, World! Hello again."
word = "Hello"
print(first_occurrence(string, word))

13. Find the last occurrence of a word in a string.

In [ ]:
def last_occurrence(s, word):
    return s.rfind(word)

string = "Hello, World! Hello again."
word = "Hello"
print(last_occurrence(string, word))

14. Split a string into a list of words.

In [ ]:
def split_string(s):
    return s.split()

string = "Hello, World! How are you?"
print(split_string(string))

15. Join a list of words into a string.

In [ ]:
def join_words(word_list):
    return " ".join(word_list)

words = ["Hello", "World", "How", "are", "you"]
print(join_words(words))

16. Convert a string where words are separated by spaces to one where words
are separated by underscores.

In [ ]:
def convert_to_underscores(s):
    return s.replace(" ", "_")

string = "Hello World How are you"
print(convert_to_underscores(string))

17. Check if a string starts with a specific word or phrase.

In [ ]:
def starts_with(s, word):
    return s.startswith(word)

string = "Hello, World!"
word = "Hello"
print(starts_with(string, word))

18. Check if a string ends with a specific word or phrase.

In [ ]:
def ends_with(s, word):
    return s.endswith(word)

string = "Hello, World!"
word = "World!"
print(ends_with(string, word))

19. Convert a string to title case (e.g., "hello world" to "Hello World").

In [ ]:
def to_title_case(s):
    return s.title()

string = "hello world"
print(to_title_case(string))

20. Find the longest word in a string.

In [ ]:
def longest_word(s):
    words = s.split()
    return max(words, key=len)

string = "Hello, I hope you are having a wonderful day!"
print(longest_word(string))

21. Find the shortest word in a string.

In [ ]:
def shortest_word(s):
    words = s.split()
    return min(words, key=len)

string = "Hello, I hope you are having a wonderful day!"
print(shortest_word(string))

22. Reverse the order of words in a string.

In [ ]:
def reverse_word_order(s):
    words = s.split()
    return " ".join(reversed(words))

string = "Hello, World! How are you?"
print(reverse_word_order(string))

23. Check if a string is alphanumeric.

In [ ]:
def is_alphanumeric(s):
    return s.isalnum()

string = "Hello123"
print(is_alphanumeric(string))

24. Extract all digits from a string.

In [ ]:
def extract_digits(s):
    return ''.join([char for char in s if char.isdigit()])

string = "Hello123, this is 2024."
print(extract_digits(string))

25. Extract all alphabets from a string.

In [ ]:
def extract_alphabets(s):
    return ''.join([char for char in s if char.isalpha()])

string = "Hello123, this is 2024."
print(extract_alphabets(string))

26. Count the number of uppercase letters in a string.

In [ ]:
def count_uppercase(s):
    return sum(1 for char in s if char.isupper())

string = "Hello World!"
print(count_uppercase(string))

27. Count the number of lowercase letters in a string.

In [ ]:
def count_lowercase(s):
    return sum(1 for char in s if char.islower())

string = "Hello World!"
print(count_lowercase(string))

28. Swap the case of each character in a string.

In [ ]:
def swap_case(s):
    return s.swapcase()

string = "Hello World!"
print(swap_case(string))

29. Remove a specific word from a string.

In [ ]:
def remove_word(s, word):
    return s.replace(word, "")

string = "Hello World, Welcome to the World!"
word = "World"
print(remove_word(string, word))

30. Check if a string is a valid email address.

In [ ]:
import re

def is_valid_email(s):
    pattern = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    return bool(re.match(pattern, s))

email = "example@example.com"
print(is_valid_email(email))

31. Extract the username from an email address string.

In [ ]:
def extract_username(email):
    return email.split('@')[0]

email = "example@example.com"
print(extract_username(email))

32. Extract the domain name from an email address string.

In [ ]:
def extract_domain(email):
    return email.split('@')[1]

email = "example@example.com"
print(extract_domain(email))

33. Replace multiple spaces in a string with a single space.

In [ ]:
def replace_multiple_spaces(s):
    return ' '.join(s.split())

string = "Hello    World!    How    are   you?"
print(replace_multiple_spaces(string))

34. Check if a string is a valid URL.

In [ ]:
import re

def is_valid_url(s):
    pattern = r'^(https?://)?(www\.)?([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,6}(/.*)?$'
    return bool(re.match(pattern, s))

url = "https://www.example.com"
print(is_valid_url(url))

35. Extract the protocol (http or https) from a URL string.

In [ ]:
import re

def extract_protocol(url):
    match = re.match(r'(https?)://', url)
    return match.group(1) if match else None

36. Find the frequency of each character in a string.

In [ ]:
from collections import Counter

def char_frequency(string):
    return dict(Counter(string))

37. Remove all punctuation from a string.

In [ ]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

38. Check if a string contains only digits.

In [ ]:
def is_digits(string):
    return string.isdigit()

39. Check if a string contains only alphabets.

In [ ]:
def is_alpha(string):
    return string.isalpha()

40. Convert a string to a list of characters.

In [ ]:
def string_to_list(string):
    return list(string)

41. Check if two strings are anagrams.

In [ ]:
def are_anagrams(str1, str2):
    return sorted(str1) == sorted(str2)

42. Encode a string using a Caesar cipher.

In [ ]:
def caesar_cipher(text, shift):
    result = ''
    for char in text:
        if char.isalpha():
            shift_base = 65 if char.isupper() else 97
            result += chr((ord(char) - shift_base + shift) % 26 + shift_base)
        else:
            result += char
    return result

43. Decode a Caesar cipher encoded string.

In [ ]:
def decode_caesar_cipher(text, shift):
    return caesar_cipher(text, -shift)

44. Find the most frequent word in a string.

In [ ]:
from collections import Counter

def most_frequent_word(text):
    words = text.split()
    word_counts = Counter(words)
    return word_counts.most_common(1)[0][0]

45. Find all unique words in a string.

In [ ]:
def unique_words(text):
    words = set(text.split())
    return list(words)

46. Count the number of syllables in a string.

In [ ]:
import re

def count_syllables(text):
    return len(re.findall(r'[aeiouAEIOU]+', text))

47. Check if a string contains any special characters.

In [ ]:
import re

def has_special_characters(string):
    return bool(re.search(r'[^a-zA-Z0-9]', string))

48. Remove the nth word from a string.

In [ ]:
def remove_nth_word(text, n):
    words = text.split()
    if 0 < n <= len(words):
        del words[n-1]
    return ' '.join(words)

49. Insert a word at the nth position in a string.

In [ ]:
def insert_nth_word(text, word, n):
    words = text.split()
    if 0 < n <= len(words):
        words.insert(n-1, word)
    else:
        words.append(word)
    return ' '.join(words)

50. Convert a CSV string to a list of lists.

In [ ]:
import csv
from io import StringIO

def csv_to_list(csv_string):
    f = StringIO(csv_string)
    reader = csv.reader(f)
    return list(reader)

List Based Practice Problem :

1. Create a list with integers from 1 to 10.

In [ ]:
numbers = list(range(1, 11))

2. Find the length of a list without using the `len()` function.

In [ ]:
def list_length(lst):
    count = 0
    for _ in lst:
        count += 1
    return count

3. Append an element to the end of a list.

In [ ]:
def append_element(lst, element):
    lst.append(element)

4. Insert an element at a specific index in a list.

In [ ]:
def insert_element(lst, index, element):
    lst.insert(index, element)

5. Remove an element from a list by its value.

In [ ]:
def remove_element(lst, element):
    lst.remove(element)

6. Remove an element from a list by its index.

In [ ]:
def remove_element_by_index(lst, index):
    del lst[index]

7. Check if an element exists in a list.

In [ ]:
def element_exists(lst, element):
    return element in lst

8. Find the index of the first occurrence of an element in a list.

In [ ]:
def find_index(lst, element):
    return lst.index(element)

9. Count the occurrences of an element in a list.

In [ ]:
def count_occurrences(lst, element):
    return lst.count(element)

10. Reverse the order of elements in a list.

In [ ]:
def reverse_list(lst):
    lst.reverse()

11. Sort a list in ascending order.

In [ ]:
def sort_list_ascending(lst):
    lst.sort()

12. Sort a list in descending order.

In [ ]:
def sort_list_descending(lst):
    lst.sort(reverse=True)

13. Create a list of even numbers from 1 to 20.

In [ ]:
even_numbers = [x for x in range(1, 21) if x % 2 == 0]

14. Create a list of odd numbers from 1 to 20.

In [ ]:
odd_numbers = [x for x in range(1, 21) if x % 2 != 0]

15. Find the sum of all elements in a list.

In [ ]:
def sum_of_elements(lst):
    return sum(lst)

16. Find the maximum value in a list.

In [ ]:
def max_value(lst):
    return max(lst)

17. Find the minimum value in a list.

In [ ]:
def min_value(lst):
    return min(lst)

18. Create a list of squares of numbers from 1 to 10.

In [ ]:
squares = [x**2 for x in range(1, 11)]

19. Create a list of random numbers.

In [ ]:
import random

random_numbers = [random.randint(1, 100) for _ in range(10)]

20. Remove duplicates from a list.

In [ ]:
def remove_duplicates(lst):
    return list(set(lst))

21. Find the common elements between two lists.

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
common_elements = [elem for elem in list1 if elem in list2]
print(common_elements)

22. Find the difference between two lists.

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
difference = [elem for elem in list1 if elem not in list2] + [elem for elem in list2 if elem not in list1]
print(difference)

23. Merge two lists.

In [ ]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
merged_list = list1 + list2
print(merged_list)

24. Multiply all elements in a list by 2.

In [ ]:
my_list = [1, 2, 3, 4, 5]
result = [x * 2 for x in my_list]
print(result)

25. Filter out all even numbers from a list.

In [ ]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
odd_numbers = [x for x in my_list if x % 2 != 0]
print(odd_numbers)

26. Convert a list of strings to a list of integers.

In [ ]:
str_list = ["1", "2", "3", "4", "5"]
int_list = [int(x) for x in str_list]
print(int_list)

27. Convert a list of integers to a list of strings.

In [ ]:
int_list = [1, 2, 3, 4, 5]
str_list = [str(x) for x in int_list]
print(str_list)

28. Flatten a nested list.

In [ ]:
nested_list = [[1, 2], [3, 4], [5, 6]]
flattened_list = [item for sublist in nested_list for item in sublist]
print(flattened_list)

29. Create a list of the first 10 Fibonacci numbers.

In [ ]:
fib = [0, 1]
for i in range(2, 10):
    fib.append(fib[i - 1] + fib[i - 2])
print(fib)

30. Check if a list is sorted.

In [ ]:
my_list = [1, 2, 3, 4, 5]
is_sorted = all(my_list[i] <= my_list[i + 1] for i in range(len(my_list) - 1))
print(is_sorted)

31. Rotate a list to the left by `n` positions.

In [ ]:
my_list = [1, 2, 3, 4, 5]
n = 2
rotated_list = my_list[n:] + my_list[:n]
print(rotated_list)

32. Rotate a list to the right by `n` positions.

In [ ]:
my_list = [1, 2, 3, 4, 5]
n = 2
rotated_list = my_list[-n:] + my_list[:-n]
print(rotated_list)

33. Create a list of prime numbers up to 50.

In [ ]:
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

primes = [x for x in range(51) if is_prime(x)]
print(primes)

34. Split a list into chunks of size `n`.

In [ ]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]
n = 3
chunks = [my_list[i:i + n] for i in range(0, len(my_list), n)]
print(chunks)

35. Find the second largest number in a list.

In [ ]:
my_list = [1, 2, 3, 4, 5]
unique_list = list(set(my_list))
unique_list.sort()
second_largest = unique_list[-2]
print(second_largest)

36. Replace every element in a list with its square.

In [ ]:
my_list = [1, 2, 3, 4, 5]
squared_list = [x**2 for x in my_list]
print(squared_list)

37. Convert a list to a dictionary where list elements become keys and their
indices become values.

In [ ]:
my_list = ['a', 'b', 'c', 'd']
my_dict = {my_list[i]: i for i in range(len(my_list))}
print(my_dict)

38. Shuffle the elements of a list randomly.

In [ ]:
import random

my_list = [1, 2, 3, 4, 5]
random.shuffle(my_list)
print(my_list)

39. Create a list of the first 10 factorial numbers.

In [ ]:
import math

factorials = [math.factorial(i) for i in range(10)]
print(factorials)

40. Check if two lists have at least one element in common.

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [4, 5, 6, 7, 8]
has_common = any(elem in list2 for elem in list1)
print(has_common)

41. Remove all elements from a list.

In [ ]:
my_list = [1, 2, 3, 4, 5]
my_list.clear()
print(my_list)

42. Replace negative numbers in a list with 0.

In [ ]:
my_list = [-1, 2, -3, 4, -5]
updated_list = [0 if x < 0 else x for x in my_list]
print(updated_list)

43. Convert a string into a list of words.

In [ ]:
my_string = "This is a sample sentence"
word_list = my_string.split()
print(word_list)

44. Convert a list of words into a string.

In [ ]:
word_list = ["This", "is", "a", "sample", "sentence"]
my_string = " ".join(word_list)
print(my_string)

45. Create a list of the first `n` powers of 2.

In [ ]:
n = 5
powers_of_2 = [2**i for i in range(n)]
print(powers_of_2)

46. Find the longest string in a list of strings.

In [ ]:
str_list = ["apple", "banana", "cherry", "kiwi"]
longest_string = max(str_list, key=len)
print(longest_string)

47. Find the shortest string in a list of strings.

In [ ]:
str_list = ["apple", "banana", "cherry", "kiwi"]
shortest_string = min(str_list, key=len)
print(shortest_string)

48. Create a list of the first `n` triangular numbers.

In [ ]:
n = 5
triangular_numbers = [sum(range(i + 1)) for i in range(n)]
print(triangular_numbers)

49. Check if a list contains another list as a subsequence.

In [ ]:
main_list = [1, 2, 3, 4, 5]
sub_list = [2, 4]

def is_subsequence(main_list, sub_list):
    it = iter(main_list)
    return all(item in it for item in sub_list)

result = is_subsequence(main_list, sub_list)
print(result)

50. Swap two elements in a list by their indices.

In [ ]:
my_list = [1, 2, 3, 4, 5]
index1, index2 = 1, 3
my_list[index1], my_list[index2] = my_list[index2], my_list[index1]
print(my_list)

Tuple Based Practice Problem :

1. Create a tuple with integers from 1 to 5.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
print(my_tuple)

2. Access the third element of a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
third_element = my_tuple[2]
print(third_element)

3. Find the length of a tuple without using the `len()` function.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
length = sum(1 for _ in my_tuple)
print(length)

4. Count the occurrences of an element in a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 2, 5, 2)
count = my_tuple.count(2)
print(count)

5. Find the index of the first occurrence of an element in a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 2, 5)
index = my_tuple.index(2)
print(index)

6. Check if an element exists in a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
exists = 3 in my_tuple
print(exists)

7. Convert a tuple to a list.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
my_list = list(my_tuple)
print(my_list)

8. Convert a list to a tuple.

In [ ]:
my_list = [1, 2, 3, 4, 5]
my_tuple = tuple(my_list)
print(my_tuple)

9. Unpack the elements of a tuple into variables.

In [ ]:
my_tuple = (1, 2, 3)
a, b, c = my_tuple
print(a, b, c)

10. Create a tuple of even numbers from 1 to 10.

In [ ]:
even_numbers = tuple(x for x in range(1, 11) if x % 2 == 0)
print(even_numbers)

11. Create a tuple of odd numbers from 1 to 10.

In [ ]:
odd_numbers = tuple(x for x in range(1, 11) if x % 2 != 0)
print(odd_numbers)

12. Concatenate two tuples.

In [ ]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
concatenated_tuple = tuple1 + tuple2
print(concatenated_tuple)

13. Repeat a tuple three times.

In [ ]:
my_tuple = (1, 2, 3)
repeated_tuple = my_tuple * 3
print(repeated_tuple)

14. Check if a tuple is empty.

In [ ]:
my_tuple = ()
is_empty = len(my_tuple) == 0
print(is_empty)

15. Create a nested tuple.

In [ ]:
nested_tuple = ((1, 2), (3, 4), (5, 6))
print(nested_tuple)

16. Access the first element of a nested tuple.

In [ ]:
nested_tuple = ((1, 2), (3, 4), (5, 6))
first_element = nested_tuple[0]
print(first_element)

17. Create a tuple with a single element.

In [ ]:
single_element_tuple = (5,)
print(single_element_tuple)

18. Compare two tuples.

In [ ]:
tuple1 = (1, 2, 3)
tuple2 = (1, 2, 3)
are_equal = tuple1 == tuple2
print(are_equal)

19. Delete a tuple.

In [ ]:
my_tuple = (1, 2, 3)
del my_tuple

20. Slice a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
sliced_tuple = my_tuple[1:4]
print(sliced_tuple)

21. Find the maximum value in a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
max_value = max(my_tuple)
print(max_value)

22. Find the minimum value in a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
min_value = min(my_tuple)
print(min_value)

23. Convert a string to a tuple of characters.

In [ ]:
my_string = "hello"
char_tuple = tuple(my_string)
print(char_tuple)

24. Convert a tuple of characters to a string.

In [ ]:
char_tuple = ('h', 'e', 'l', 'l', 'o')
my_string = ''.join(char_tuple)
print(my_string)

25. Create a tuple from multiple data types.

In [ ]:
my_tuple = (1, "hello", 3.14, True)
print(my_tuple)

26. Check if two tuples are identical.

In [ ]:
tuple1 = (1, 2, 3)
tuple2 = (1, 2, 3)
are_identical = tuple1 == tuple2
print(are_identical)

27. Sort the elements of a tuple.

In [ ]:
my_tuple = (5, 3, 8, 1, 2)
sorted_tuple = tuple(sorted(my_tuple))
print(sorted_tuple)

28. Convert a tuple of integers to a tuple of strings.

In [ ]:
int_tuple = (1, 2, 3, 4, 5)
str_tuple = tuple(str(x) for x in int_tuple)
print(str_tuple)

29. Convert a tuple of strings to a tuple of integers.

In [ ]:
str_tuple = ("1", "2", "3", "4", "5")
int_tuple = tuple(int(x) for x in str_tuple)
print(int_tuple)

30. Merge two tuples.

In [ ]:
tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)
merged_tuple = tuple1 + tuple2
print(merged_tuple)

31. Flatten a nested tuple.

In [ ]:
nested_tuple = ((1, 2), (3, 4), (5, 6))
flattened_tuple = tuple(item for subtuple in nested_tuple for item in subtuple)
print(flattened_tuple)

32. Create a tuple of the first 5 prime numbers.

In [ ]:
prime_numbers = (2, 3, 5, 7, 11)
print(prime_numbers)

33. Check if a tuple is a palindrome.

In [ ]:
my_tuple = (1, 2, 3, 2, 1)
is_palindrome = my_tuple == my_tuple[::-1]
print(is_palindrome)

34. Create a tuple of squares of numbers from 1 to 5.

In [ ]:
squares_tuple = tuple(x**2 for x in range(1, 6))
print(squares_tuple)

35. Filter out all even numbers from a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 5, 6)
odd_tuple = tuple(x for x in my_tuple if x % 2 != 0)
print(odd_tuple)

36. Multiply all elements in a tuple by 2.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
multiplied_tuple = tuple(x * 2 for x in my_tuple)
print(multiplied_tuple)

37. Create a tuple of random numbers.

In [ ]:
import random

random_tuple = tuple(random.randint(1, 100) for _ in range(5))
print(random_tuple)

38. Check if a tuple is sorted.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
is_sorted = all(my_tuple[i] <= my_tuple[i + 1] for i in range(len(my_tuple) - 1))
print(is_sorted)

39. Rotate a tuple to the left by `n` positions.

In [1]:
my_tuple = (1, 2, 3, 4, 5)
n = 2
rotated_tuple = my_tuple[n:] + my_tuple[:n]
print(rotated_tuple)

(3, 4, 5, 1, 2)

40. Rotate a tuple to the right by `n` positions.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
n = 2
rotated_tuple = my_tuple[-n:] + my_tuple[:-n]
print(rotated_tuple)

41. Create a tuple of the first 5 Fibonacci numbers.

In [ ]:
fibonacci_tuple = (0, 1, 1, 2, 3)
print(fibonacci_tuple)

42. Create a tuple from user input.

In [ ]:
user_input = input("Enter values separated by space: ")
user_tuple = tuple(user_input.split())
print(user_tuple)

43. Swap two elements in a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
index1, index2 = 1, 3
temp_list = list(my_tuple)
temp_list[index1], temp_list[index2] = temp_list[index2], temp_list[index1]
swapped_tuple = tuple(temp_list)
print(swapped_tuple)

44. Reverse the elements of a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
reversed_tuple = my_tuple[::-1]

45. Create a tuple of the first `n` powers of 2.

In [ ]:
n = 5
powers_of_2 = tuple(2**i for i in range(n))

46. Find the longest string in a tuple of strings.

In [ ]:
my_tuple = ("apple", "banana", "cherry", "kiwi")
longest_string = max(my_tuple, key=len)

47. Find the shortest string in a tuple of strings.

In [ ]:
my_tuple = ("apple", "banana", "cherry", "kiwi")
shortest_string = min(my_tuple, key=len)

48. Create a tuple of the first `n` triangular numbers.

In [ ]:
n = 5
triangular_numbers = tuple((i * (i + 1)) // 2 for i in range(1, n + 1))

49. Check if a tuple contains another tuple as a subsequence.

In [ ]:
tuple1 = (1, 2, 3, 4, 5)
tuple2 = (2, 4)
result = all(x in tuple1 for x in tuple2)

50. Create a tuple of alternating 1s and 0s of length `n`.

In [ ]:
n = 6
alternating_tuple = tuple(1 if i % 2 == 0 else 0 for i in range(n))

Set Based Practice Problem :

1. Create a set with integers from 1 to 5.

In [ ]:
my_set = {1, 2, 3, 4, 5}

2. Add an element to a set.

In [ ]:
my_set = {1, 2, 3, 4, 5}
my_set.add(6)

3. Remove an element from a set.

In [ ]:
my_set = {1, 2, 3, 4, 5}
my_set.remove(3)

4. Check if an element exists in a set.

In [ ]:
my_set = {1, 2, 3, 4, 5}
exists = 3 in my_set

5. Find the length of a set without using the `len()` function.

In [ ]:
my_set = {1, 2, 3, 4, 5}
length = sum(1 for _ in my_set)

6. Clear all elements from a set.

In [ ]:
my_set = {1, 2, 3, 4, 5}
my_set.clear()

7. Create a set of even numbers from 1 to 10.

In [ ]:
even_numbers = {2, 4, 6, 8, 10}

8. Create a set of odd numbers from 1 to 10.

In [ ]:
odd_numbers = {1, 3, 5, 7, 9}

9. Find the union of two sets.

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1 | set2

10. Find the intersection of two sets.

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
intersection_set = set1 & set2

11. Find the difference between two sets.

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
difference_set = set1 - set2

12. Check if a set is a subset of another set.

In [ ]:
set1 = {1, 2, 3}
set2 = {1, 2, 3, 4, 5}
is_subset = set1.issubset(set2)

13. Check if a set is a superset of another set.

In [ ]:
set1 = {1, 2, 3, 4, 5}
set2 = {2, 3}
is_superset = set1.issuperset(set2)

14. Create a set from a list.

In [ ]:
my_list = [1, 2, 3, 4, 5]
my_set = set(my_list)

15. Convert a set to a list.

In [ ]:
my_set = {1, 2, 3, 4, 5}
my_list = list(my_set)

16. Remove a random element from a set.

In [ ]:
import random
my_set = {1, 2, 3, 4, 5}
my_set.remove(random.choice(list(my_set)))

17. Pop an element from a set.

In [ ]:
my_set = {1, 2, 3, 4, 5}
popped_element = my_set.pop()

18. Check if two sets have no elements in common.

In [ ]:
set1 = {1, 2, 3}
set2 = {4, 5, 6}
no_common_elements = set1.isdisjoint(set2)

19. Find the symmetric difference between two sets.

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
symmetric_difference = set1 ^ set2

20. Update a set with elements from another set.

In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
set1.update(set2)

21. Create a set of the first 5 prime numbers.

In [ ]:
prime_numbers = {2, 3, 5, 7, 11}

22. Check if two sets are identical.

In [ ]:
set1 = {1, 2, 3}
set2 = {1, 2, 3}
are_identical = set1 == set2

23. Create a frozen set.

In [ ]:
my_frozenset = frozenset([1, 2, 3, 4, 5])

24. Check if a set is disjoint with another set.

In [ ]:
set1 = {1, 2, 3}
set2 = {4, 5, 6}
is_disjoint = set1.isdisjoint(set2)

25. Create a set of squares of numbers from 1 to 5.

In [ ]:
squares_set = {x**2 for x in range(1, 6)}

26. Filter out all even numbers from a set.

In [ ]:
my_set = {1, 2, 3, 4, 5, 6}
odd_numbers = {x for x in my_set if x % 2 != 0}

27. Multiply all elements in a set by 2.

In [ ]:
my_set = {1, 2, 3, 4, 5}
doubled_set = {x * 2 for x in my_set}

28. Create a set of random numbers.

In [ ]:
import random
random_numbers = {random.randint(1, 10) for _ in range(5)}

29. Check if a set is empty.

In [ ]:
my_set = {1, 2, 3}
is_empty = len(my_set) == 0

30. Create a nested set (hint: use frozenset).

In [ ]:
nested_set = {frozenset({1, 2}), frozenset({3, 4})}

31. Remove an element from a set using the discard method.

In [ ]:
my_set = {1, 2, 3, 4, 5}
my_set.discard(3)

32. Compare two sets.

In [ ]:
set1 = {1, 2, 3}
set2 = {2, 3, 4}
comparison = set1 == set2

33.Create a set from a string.

In [ ]:
my_string = "hello"
my_set = set(my_string)

34. Convert a set of strings to a set of integers.

In [ ]:
string_set = {"1", "2", "3"}
integer_set = {int(x) for x in string_set}

35. Convert a set of integers to a set of strings.

In [ ]:
integer_set = {1, 2, 3}
string_set = {str(x) for x in integer_set}

36. Create a set from a tuple.

In [ ]:
my_tuple = (1, 2, 3, 4, 5)
my_set = set(my_tuple)

37. Convert a set to a tuple.

In [ ]:
my_set = {1, 2, 3, 4, 5}
my_tuple = tuple(my_set)

38. Find the maximum value in a set.

In [ ]:
my_set = {1, 2, 3, 4, 5}
max_value = max(my_set)

39. Find the minimum value in a set.

In [ ]:
my_set = {1, 2, 3, 4, 5}
min_value = min(my_set)

40. Create a set from user input.

In [ ]:
user_input = input("Enter numbers separated by spaces: ")
user_set = {int(x) for x in user_input.split()}

41. Check if the intersection of two sets is empty.

In [ ]:
set1 = {1, 2, 3}
set2 = {4, 5, 6}
is_intersection_empty = set1.isdisjoint(set2)

42. Create a set of the first 5 Fibonacci numbers.

In [ ]:
fibonacci_set = {0, 1, 1, 2, 3}

43. Remove duplicates from a list using sets.

In [ ]:
my_list = [1, 2, 3, 2, 4, 5, 5]
unique_elements = list(set(my_list))

44. Check if two sets have the same elements, regardless of their count.

In [ ]:
set1 = {1, 2, 3, 4}
set2 = {4, 3, 2, 1}
are_equal = set1 == set2

45. Create a set of the first `n` powers of 2.

In [ ]:
n = 5
powers_of_2 = {2**i for i in range(n)}

46. Find the common elements between a set and a list.

In [ ]:
my_set = {1, 2, 3, 4, 5}
my_list = [3, 4, 6, 7]
common_elements = my_set.intersection(my_list)

47. Create a set of the first `n` triangular numbers.

In [ ]:
n = 5
triangular_numbers = {i * (i + 1) // 2 for i in range(1, n + 1)}

48. Check if a set contains another set as a subset.

In [ ]:
set1 = {1, 2, 3, 4, 5}
set2 = {2, 3}
is_subset = set2.issubset(set1)

49. Create a set of alternating 1s and 0s of length `n`.

In [ ]:
n = 6
alternating_set = {1 if i % 2 == 0 else 0 for i in range(n)}

50. Merge multiple sets into one.

In [ ]:
set1 = {1, 2, 3}
set2 = {4, 5}
set3 = {6, 7}
merged_set = set1 | set2 | set3